server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

douyinmall:
  jwt:
    location: classpath:douyinmall.jks # 秘钥地址
    alias: hmall # 秘钥别名
    password: hmall123 # 秘钥文件密码
    tokenTTL: 30m # 登录有效期
  auth:
    excludePaths: # 无需登录校验的路径
      - /search/**
      - /users/api/login/**
      - /users/api/register
      - /products/api/select
      - /captcha