server:
  port: 8079
  max-http-header-size: 65536  # 恢复默认值

spring:
  cloud:
    sentinel:
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: sentinel-rules
            groupId: DEFAULT_GROUP
            rule-type: flow
      transport:
        dashboard: localhost:8080  # Sentinel控制台地址
        port: 8719                # 本地启动的HTTP Server端口（默认8719）
      eager: true
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      httpclient:
        max-header-size: 65536  # 恢复默认值


douyinmall:
  jwt:
    location: classpath:douyinmall.jks # 秘钥地址
    alias: hmall # 秘钥别名
    password: hmall123 # 秘钥文件密码
    tokenTTL: 30m # 登录有效期
  auth:
    excludePaths:
      - /alipay/*
      - /*/v3/api-docs/**
      - /v3/api-docs/**
      - /doc.html
      - /favicon.ico
      - /swagger-resources
      - /swagger-resources/**
      - /webjars/**
      - /users/api/login/**        # 登录接口
      - /users/api/register     # 注册接口
      - /search/**
      - /products/api/**
      - /products/api/categories/select/**
      - /captcha
      - /ai/api/**
      - /users/api/findComment
      - /users/api/findSecondComment
      - /users/api/getCommentCount/**


