server:
  port: 8084  # 每个服务的端口号要不同

spring:
  application:
    name: mall-payment  # 必须设置应用名，Nacos会根据这个名称查找配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos服务地址
      config:
        server-addr: 127.0.0.1:8848  # Nacos配置中心地址
        file-extension: yaml         # 配置文件格式
        namespace:                   # 命名空间ID（如果有）
        group: DEFAULT_GROUP         # 配置分组（默认DEFAULT_GROUP）
  config:
    import: optional:nacos:${spring.application.name}  # 关键配置，导入Nacos配置
  datasource:
    url: jdbc:mysql://${mall.db.host:127.0.0.1}:${mall.db.port:3306}/${mall.db.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${mall.db.user:root}
    password: ${mall.db.password:root}

mall:
  db:
    host: 127.0.0.1
    #host: 192.168.145.128
    database: mall-payment
    user: root
    password: root
  swagger:
    title: "抖音电商商品服务接口文档"
    description: "抖音电商商品服务接口文档"
    package: com.mall.payment.controller

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

knife4j:
  enable: true
  openapi:
    title: ${mall.swagger.title:抖音电商接口文档}
    description: ${mall.swagger.description:抖音电商接口文档}
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - ${mall.swagger.package}