server:
  port: 8084  # 每个服务的端口号要不同

spring:
  application:
    name: mall-payment  # 必须设置应用名，Nacos会根据这个名称查找配置
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos服务地址
      config:
        server-addr: 127.0.0.1:8848  # Nacos配置中心地址
        file-extension: yaml         # 配置文件格式
        namespace:                   # 命名空间ID（如果有）
        group: DEFAULT_GROUP         # 配置分组（默认DEFAULT_GROUP）
  config:
    import: optional:nacos:${spring.application.name}  # 关键配置，导入Nacos配置
  datasource:
    url: jdbc:mysql://${mall.db.host:127.0.0.1}:${mall.db.port:3306}/${mall.db.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${mall.db.user:root}
    password: ${mall.db.password:root}

mall:
  db:
    host: 127.0.0.1
    #host: 192.168.145.128
    database: mall-payment
    user: root
    password: root
  swagger:
    title: "抖音电商商品服务接口文档"
    description: "抖音电商商品服务接口文档"
    package: com.mall.payment.controller

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto


alipay:
  appId: 2021000147694905
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCGN1hLQgQNJn37haUrrAnjEZM978v5Wp3i0fZMrKtUnC+2Y/LcOIJdEejGA0tNkZIZPk55ACbWLMzBAyMSM2q0DiT9KFua71hMjhrvwRVXWiMInjlqtA3SgtOq50kNHYFDaDBPjnJzWe7+oFl+626N649+CY9xVwiLyfvofJ0Sc4+Xv6ZQgcfyNr7gi08hSFtDiUuERl22e1PgHYyh9CsEyFKBuDE8OsrjnpnAY4qihS9NjILoEXTciXdipq+VRq7MKOIuv2cp6xREOUeFThk/lnX2q8BKE0dx/lCm5NCPQq0NpAFy+bRaISo0d6HYUwdJZbChuUKZK+X1lMiZa/EJAgMBAAECggEAZJKSWgqE6KnAW7qgs2H+IqXn1NCc4yQxDWdSDdCRrhw/cIfi03yQy1cBO2f6hIyhksLqoKcpcvItGDDWlevreDLlKsKUKjxRyUPvEVt5N3S2rd2Kntd/SBB6tiULy4UheLZZBTRztNZeTXUwuveGZ1httP9K+p5CLCXV2zeNp+XUlLt1BhV4NRlkHwuDLiDeFdQXNoGVk5Xe2M+vnbAcBvGM4VRIy9lvX3KyHshY6LNEWImUX/xpSBaWU9vwa66pMwEzo7+umjaImvC0klADq703wFcqEe1P0OmUnS54IL6RdnypBuyU2RIQW0AqDdeWL8Gvw+be8LGChRuZuCv9JQKBgQC6ZogjEJG39LTCH3qEFppGafPb/ifxP0Gm3S+iuhp7Tb0Fz5RX4S2iAto96u9cTmRemzvHrjuRFPxHeNlgFCCsncyHTMdTMOnwnHtxwxHH4zviu+IuFM36CrETL+4tmAcmaq8GUZxBWryR63Musoh9RCQVX5QV3Jb5ol4ZuLe6BwKBgQC4VKtm3Nvhv7oFAlU7Zv1bpy3pngAK4npu8B5S2C/gu0jQCmIPHuoMt/MgN3bXVepQbdl/TlQZBXnltJZe08BmP+JpYUgpcJ5pyXuk60YPkJ0YI880QXDaKocZuJvk5basm2MfHKTp+StRjhc5nOWxZZ4F7T/681iWhyzTkTl4bwKBgFjOsN3D7ykttVEnnj+AZVBW+pA9rtoJwUW27BMjh6pnhz9Vft+/sPYXVdNaM2BPGRLZ8slYAZlF3kxPD4HvFQIozGFJ+01vaIXyh/3Tao1JfiawTTqXPut6XJM/qsKeRAnRmkHwb/nTOTRscRw2g0DrTiXAu9UOm/+jlCG9GAvRAoGAR1bdj03i+5fMUqv4eKj/XT1yk3vG4G+Omujrk3x/6yYQpBOgp+F7C7kVq15L7EMgEEizaIXUHmr0Jmah28lwKSKIaehwmTkw1hhYdhdoYhXB9tnFE6BQIN9csiO0kf4lmN/6mMvpN3Rrw4COlImYi/OcGQcdP+52VquyOZ928pkCgYAxSuEw0WL/HqhePIFZFP4F4o9S/naPE34EhXchI5DmlyBAGjvPYr94eS5Iltxubifn1sJITdcLCLbMtUnJ8KHr8CpnS07PZJdRCLaXBsPnkEukiJgcI5o3asd8OV5TNaOP2C24ZTl5TTX5ske7VJ1+uGjF5XKk97qzDUtqEx+M6Q==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhjdYS0IEDSZ9+4WlK6wJ4xGTPe/L+Vqd4tH2TKyrVJwvtmPy3DiCXRHoxgNLTZGSGT5OeQAm1izMwQMjEjNqtA4k/Shbmu9YTI4a78EVV1ojCJ45arQN0oLTqudJDR2BQ2gwT45yc1nu/qBZfutujeuPfgmPcVcIi8n76HydEnOPl7+mUIHH8ja+4ItPIUhbQ4lLhEZdtntT4B2MofQrBMhSgbgxPDrK456ZwGOKooUvTYyC6BF03Il3YqavlUauzCjiLr9nKesURDlHhU4ZP5Z19qvAShNHcf5QpuTQj0KtDaQBcvm0WiEqNHeh2FMHSWWwoblCmSvl9ZTImWvxCQIDAQAB
  notifyUrl: http://ictizc.natappfree.cc/alipay/notify


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

knife4j:
  enable: true
  openapi:
    title: ${spring.application.name}接口文档
    description: ${spring.application.name}接口文档
    version: 1.0.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.mall.payment.controller