server:
  port: 8083  #每个服务的端口号要不同
spring:
  datasource:
    url: jdbc:mysql://${mall.db.host:127.0.0.1}:${mall.db.port:3306}/${mall.db.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${mall.db.user:root}
    password: ${mall.db.password:123}

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

knife4j:
  enable: true
  openapi:
    title: ${mall.swagger.title:抖音电商接口文档}
    description: ${mall.swagger.description:抖音电商接口文档}
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - ${mall.swagger.package}