server:
  port: 8085
spring:
  application:
    name: mall-cart
  datasource:
    url: jdbc:mysql://localhost:3306/mall-cart?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password:  # 如果有密码则填写
    database: 0

logging:
  level:
    root: INFO
    com.mall.ai: DEBUG  # DEBUG 级别以查看详细日志
    com.mall.ai.service: DEBUG  # 特别是服务层的日志
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: D:/log/log.log

