server:
  port: 8081

spring:
  application:
    name: mall-user
  mail:
    host: smtp.163.com
    username: jzk1310153668@163.com
    password: VHpJzhWYx2Bk2rc9
    default-encoding: utf-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: true

  #  profiles:
#    active: dev
  datasource:
    # url: jdbc:mysql://localhost:3306/mall-user?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/mall-user?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    #password: 123
  data:
    redis:
      host: localhost
      database: 0

douyinmall:
  jwt:
    location: classpath:douyinmall.jks # 秘钥地址
    alias: hmall # 秘钥别名
    password: hmall123 # 秘钥文件密码
    tokenTTL: 300m # 登录有效期

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto