mall:
  db:
    host: 127.0.0.1
    #host: 192.168.145.128
    database: mall-product
    user: root
    password: root
  swagger:
    title: "抖音电商商品服务接口文档"
    description: "抖音电商商品服务接口文档"
    package: com.mall.product.controller