server:
  port: 8088
spring:
  application:
    name: mall-ai
  datasource:
    url: jdbc:mysql://localhost:3306/mall_ai_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

deepseek:
  api:
    key: sk-acb3b1ed8179427cb37105e225f216e9
    url: https://api.deepseek.com/v1/chat/completions
    timeout: 60000
    retry: 3
    connect-timeout: 60000
    read-timeout: 60000
    write-timeout: 60000

logging:
  level:
    root: INFO
    com.mall.ai: DEBUG  # DEBUG 级别以查看详细日志
    com.mall.ai.service: DEBUG  # 特别是服务层的日志
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: D:/log/log.log

