server:
  port: 8088
spring:
  application:
    name: mall-ai
  datasource:
    url: jdbc:mysql://localhost:3306/mall_ai_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

deepseek:
  api:
    key: sk-acb3b1ed8179427cb37105e225f216e9
    url: https://api.deepseek.com/v1/chat/completions
    timeout: 60000
    retry: 3
    connect-timeout: 60000
    read-timeout: 60000
    write-timeout: 60000


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

knife4j:
  enable: true
  setting:
    language: zh_cn
  openapi:
    title: ${spring.application.name}接口文档
    description: ${spring.application.name}接口文档
    version: 1.0.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.mall.ai.controller

logging:
  level:
    root: INFO
    com.mall.ai: DEBUG  # DEBUG 级别以查看详细日志
    com.mall.ai.service: DEBUG  # 特别是服务层的日志
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: D:/log/log.log

