server:
  port: 8089

spring:
  application:
    name: mall-order
  datasource:
    url: jdbc:mysql://localhost:3306/mall-order?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    #    url: jdbc:mysql://192.168.145.128:3306/mall-user?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    #    password: 123
  data:
    redis:
      host: localhost
      database: 0

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

knife4j:
  enable: true
  setting:
    language: zh_cn
  openapi:
    title: ${spring.application.name}接口文档
    description: ${spring.application.name}接口文档
    version: 1.0.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.mall.order.controller